# ì—ë””í„°ì—ì„œ regex ê²€ìƒ‰ìœ¼ë¡œ replace í•˜ê¸° (** ** â†’ <mark></mark>)
# \*\*(.*?)\*\*
# <mark>$1</mark>

# ì—ë””í„°ì—ì„œ regex ê²€ìƒ‰ìœ¼ë¡œ replace í•˜ê¸° (<mark></mark> â†’ ** **)
# <mark>(.*?)<\/mark>
# **$1**

# Site
repository: dev-loggi/dev-loggi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: ì¡°ì„±ë¡
title: Android Developer
email: jsl663663@gmail.com
website: github.com/dev-loggi

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: dev-loggi
# youtube_username: user-pk6no1ub6p
# twitter_username: facespics
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Blog
  icon: fas fa-blog
  url: https://jsl663.tistory.com
- title: YouTube Link
  icon: fab fa-youtube
  url: https://www.youtube.com/channel/UCYPnZS7wsGgdaCM1GYAaKrg

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  ì•ˆë…•í•˜ì„¸ìš”. ë””ìì¸ì— ê´€ì‹¬ì´ ë§ì€ ì•ˆë“œë¡œì´ë“œ ê°œë°œì ì¡°ì„±ë¡ì…ë‹ˆë‹¤<br/><br/>
  
  í•™ë¶€ ì‹œì ˆ C#ìœ¼ë¡œ [ìœˆë„ìš° ê²Œì„](https://youtu.be/vx7aT_5YpIA)ì„ ë§Œë“¤ ë•Œë¶€í„° ë””ìì¸ì— ëŒ€í•œ ë‚¨ë‹¤ë¥¸ ê´€ì‹¬ì„ ë³´ì´ë©° **UI/UX ë° ë””ìì¸ íŠ¸ë Œë“œ**ì˜ ë†’ì€ ì´í•´ë„ë¥¼ ê°–ê²Œ ë˜ì—ˆìŠµë‹ˆë‹¤.<br/>
  ì´ëŠ” ì•± ê°œë°œì—ì„œë„ ì´ì–´ì ¸ **ì•ˆë“œë¡œì´ë“œ ë·° ì‹œìŠ¤í…œì— ëŒ€í•œ ì´í•´ë„**ì™€ ë‹¤ì–‘í•œ CustomView í™œìš© ë° Animation/Transition, ìœ ì €ì˜ í„°ì¹˜ ì¸í„°ë ‰ì…˜, ê·¸ë¦¬ê³  ê³µí†µ ë””ìì¸ ì‹œìŠ¤í…œ ëª¨ë“ˆí™” ë“± **UI ê°œë°œ ì—­ëŸ‰**ì„ ê¾¸ì¤€íˆ ì¦ì§„í•´ì™”ìŠµë‹ˆë‹¤.
  <br/><br/>
  
  **í”„ë¡œê·¸ë˜ë° ì—­ëŸ‰ê³¼ ê°œë°œ ê¸°ìˆ ë ¥** í–¥ìƒì— ëŒ€í•´ì„œë„ ê¾¸ì¤€íˆ ë…¸ë ¥í•´ ì™”ìŠµë‹ˆë‹¤.<br/>
  IT íšŒì‚¬ì—ì„œ 6ê°œì›”ê°„ ì¸í„´ìœ¼ë¡œ ê·¼ë¬´í•˜ë©° **ì•± ì„œë¹„ìŠ¤ ê°œë°œ ë° ë°°í¬ ê²½í—˜**ì„ í•˜ì˜€ìœ¼ë©°, ì´í›„ì—ë„ ì§€ì†ì ì¸ í”„ë¡œì íŠ¸ ê°œë°œì„ í†µí•´ ë””ìì¸ íŒ¨í„´ê³¼ í´ë¦° ì•„í‚¤í…ì²˜, Jetpack ë¼ì´ë¸ŒëŸ¬ë¦¬ ë“± ìµœì‹  **ê³ ê¸‰ ê¸°ìˆ  ìŠ¤íƒ**ì˜ í™œìš© ëŠ¥ë ¥ê³¼ ì´í•´ë„ë¥¼ ë†’ì—¬ì™”ìŠµë‹ˆë‹¤.
  <br/><br/>
  
  ìµœê·¼ì—ëŠ” íŒ€ í”„ë¡œì íŠ¸ì—ì„œ í”„ë¡ íŠ¸/ë°±ì—”ë“œ ê°œë°œì„ ë„˜ì–´ **ê¸°ìˆ  íŒ€ì¥**ì˜ ì—­í• ì„ ë§¡ì•„ ì‹œìŠ¤í…œì„ ì„¤ê³„í•˜ê³ , íŒ€ì— ê¸°ìˆ ì ì¸ ì§€ì›ì„ í•˜ë©° ê°œë°œì— ëŒ€í•œ ì‹œì•¼ë¥¼ í•œì¸µ ë” ë„“í ìˆ˜ ìˆì—ˆë˜ ê²½í—˜ì„ ê°–ê³  ìˆìŠµë‹ˆë‹¤.

content:
  # Experience
  - title: Experience
    layout: list
    content:
      - layout: left
        title: íŒê²Œì•„ì†”ë£¨ì…˜
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: ì•ˆë“œë¡œì´ë“œ ì•± ê°œë°œ (ì¸í„´)
        caption: 2017.03 - 2017.08
        additional_links:
          - title: Google Play Link
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.goalgetter.goalgetterapp
        quote: >
          ì†Œì…œ ëª©í‘œ ì¼ê¸° "GoalGetter" SNS ëª¨ë°”ì¼ ì•± ì„œë¹„ìŠ¤ ê°œë°œ
        description: |
          __`Android` `Java`__
          - ì„œë¹„ìŠ¤ ì´ˆê¸° 1.0 ë²„ì „ ê°œë°œ ë° í…ŒìŠ¤íŠ¸, ì˜ë¢°ì¸ í”¼ë“œë°± ë°˜ì˜, ë°°í¬ ì‘ì—…
          - íšŒì›, ê²Œì‹œë¬¼, ë©”ì‹ ì €, ê´‘ê³  ë“± ì´ 23ê°œ í™”ë©´ ë° ê¸°ëŠ¥ ê°œë°œ
          - ConstraintLayout, RecyclerView ë„ì…
          - SQLiteë¥¼ í™œìš©í•˜ì—¬ ë©”ì‹ ì € ì„±ëŠ¥ ê°œì„ 
          
          [ê°œë°œ ë‚´ìš© ë”ë³´ê¸°](https://dev-loggi.notion.site/GoalGetter-d3a18b465fad46519bf5f29e45e6c904?pvs=4)

  # Education
  - title: Education
    layout: list
    content:
      - layout: left
        title: KT AIVLE School 3ê¸°
        caption: 2023.02 - 2023.07
        sub_title: KT
        link: https://aivle.kt.co.kr/
        description: |
          - ê¸°ì—… ì‹¤ë¬´í˜• AI ê°œë°œì êµìœ¡
          - AI ëª¨ë¸ë§ì„ ìœ„í•œ ë°ì´í„° ë¶„ì„, ë¨¸ì‹ ëŸ¬ë‹, ë”¥ëŸ¬ë‹(CV, NLP) ì´ë¡  ë° ì‹¤ìŠµ
          - AI ì„œë¹„ìŠ¤ ê°œë°œì„ ìœ„í•œ MLOps, FE, BE, AWS í´ë¼ìš°ë“œ ì´ë¡  ë° ì‹¤ìŠµ
          - êµê³¼ëª©ë³„ í•™ìŠµ ê³¼ì •ì— ëŒ€í•œ ì‹¤ìŠµì„ ìœ„í•œ ë¯¸ë‹ˆ í”„ë¡œì íŠ¸ ìˆ˜í–‰
          - ë¹…í”„ë¡œì íŠ¸, AI ê¸°ë°˜ ëŒ€í˜•ìƒí™œíê¸°ë¬¼ ê°„í¸ ë°°ì¶œ ì•± â€œí¼ë‹ˆë²„ë‹ˆâ€ (ìš°ìˆ˜ìƒğŸ†)
      - layout: left
        title: SW ì•Œê³ ë¦¬ì¦˜ íŠ¹ê°•
        caption: 2022.07 - 2023.08 (6ì£¼)
        sub_title: ì‚¼ì„±ì „ì
        description: |
          - SW ìë£Œêµ¬ì¡° ë° ì•Œê³ ë¦¬ì¦˜ ì´ë¡  ê°•ì˜ ë° ì‹¤ì „ ë¬¸ì œ í’€ì´
          - ì£¼ì–´ì§„ ë¬¸ì œì— ì í•©í•œ ìë£Œêµ¬ì¡°ë¥¼ ì§ì ‘ ì„¤ê³„ ë° êµ¬í˜„
          - SW Expert Academy - Professional(Level B) ì·¨ë“

  # Projects
  - title: Projects
    layout: list
    content:
      # í¼ë‹ˆë²„ë‹ˆ
      - layout: left
        title: í¼ë‹ˆë²„ë‹ˆ
        caption: 2023.06 - 2023.07
        sub_title: Tech Lead, Android
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/KT-AIVLE-3rd-AI-Team10/funibuni-fe-android
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/N-wBxebZWTY
        quote: >
          AI ê¸°ë°˜ ëŒ€í˜•ìƒí™œíê¸°ë¬¼ ê°„í¸ ë°°ì¶œ ì•±
        description: |
          __`Android` `Kotlin` `MVVM` `Clean Architecture`__
          - KT AIVLE School 6ì¸ íŒ€ í”„ë¡œì íŠ¸ (ìš°ìˆ˜ìƒğŸ†)
          - AI ëª¨ë¸ ì„¤ê³„, ì‹œìŠ¤í…œ ì•„í‚¤í…ì²˜, ERD, API ì„¤ê³„, í…ŒìŠ¤íŠ¸, ì„œë²„ êµ¬ì¶• ë“± <mark>ê¸°ìˆ  íŒ€ì¥ ì—­í• </mark> ìˆ˜í–‰
          - <mark>Coroutines & Flow</mark> ë¥¼ í™œìš©í•˜ì—¬ ë¹„ë™ê¸° í”„ë¡œê·¸ë˜ë°ê³¼ <mark>UiState ê´€ë¦¬</mark>
          - í„°ì¹˜ ì• ë‹ˆë©”ì´ì…˜ íš¨ê³¼, ì»¤ìŠ¤í…€ ë‹¤ì´ì–¼ë¡œê·¸ ë“± <mark>ê³µí†µ Design System ëª¨ë“ˆí™”</mark>
      # ë™ì˜ìƒ Ctrl+F
      - layout: left
        title: ë™ì˜ìƒ Ctrlï¼‹F
        caption: 2023.04 - 2023.06
        sub_title: Tech Lead, Frontend
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/Video-CtrlF/video-ctrlf-introduce
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/UvRD_n5bfaQ
        quote: >
          AI ê¸°ë°˜ ìœ íŠœë¸Œ ë™ì˜ìƒ ì† í…ìŠ¤íŠ¸ ê²€ìƒ‰ ì„œë¹„ìŠ¤ (Chrome Extensions)
        description: |
          __`HTML` `CSS` `JavaScript`__
          - K-Digital Training Hackathon 5ì¸ íŒ€ í”„ë¡œì íŠ¸ (ì˜ˆì„  í†µê³¼)
          - ìœ íŠœë¸Œ ë™ì˜ìƒì—ì„œ í…ìŠ¤íŠ¸ ê²€ìƒ‰ ê¸°ëŠ¥ (Ctrl+F) ë° í™”ë©´ êµ¬í˜„
          - SPA, CORS ë¬¸ì œ í•´ê²°
          - ì´ë¯¸ì§€ ìœ ì‚¬ë„ ì•Œê³ ë¦¬ì¦˜ SSIM ì„ í†µí•´ AI ëª¨ë¸ ì¶”ë¡  ì‹œê°„ì„ ëŒ€í­ ë‹¨ì¶•
          - í”„ë ˆì„ë§ˆë‹¤ ì—°ì†ì ìœ¼ë¡œ ì¤‘ë³µë˜ëŠ” í…ìŠ¤íŠ¸ ë°©ì§€ë¥¼ ìœ„í•œ ì•Œê³ ë¦¬ì¦˜ êµ¬í˜„
      # ë­ë”ë¼
      - layout: left
        title: ë­ë”ë¼
        caption: 2021.11 - 2022.03
        sub_title: Android, Backend
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/dev-loggi/mwodeola-android
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/JI3wjMUU__s
        quote: >
          ì›¹ì‚¬ì´íŠ¸ ë° ì–´í”Œ ê³„ì •ì˜ ì•„ì´ë””/ë¹„ë°€ë²ˆí˜¸ ê¸°ë¡ ê´€ë¦¬ ì•ˆë“œë¡œì´ë“œ ì•±
        description: |
          __`Android` `Kotlin` `MVP`__
          - ì•± ì„œë¹„ìŠ¤ ê°œë°œ 1ì¸ í”„ë¡œì íŠ¸ (ê¸°íš, ì„¤ê³„, ë””ìì¸, ë³´ì•ˆ, ì•±, ì„œë²„ ê°œë°œ)
          - íšŒì› ê¸°ëŠ¥, ê³„ì • ì•„ì´ë””/ë¹„ë°€ë²ˆí˜¸ ì €ì¥, ì•± í™”ë©´ ì ê¸ˆ, ê³„ì • ë¹„ë°€ë²ˆí˜¸ í™•ì¸ ì‹œ ì•”í˜¸ ì¸ì¦(ì´ì¤‘ ì ê¸ˆ), ë¡œê·¸ì¸ ìë™ ì™„ì„± ì„œë¹„ìŠ¤(Android Autofillframework) ê¸°ëŠ¥ ê°œë°œ
          - ë‹¤ì¤‘ ê³„ì •, SNS ì•„ì´ë””ë¡œ ê°€ì…í•œ ê³„ì •ì— ëŒ€í•œ ë³„ë„ ë¡œì§ ë° DB ì„¤ê³„
          - UI/UX í–¥ìƒì„ ìœ„í•´ ê° ê³„ì •ë§ˆë‹¤ ì¸ë„¤ì¼ ì•„ì´ì½˜ ì‚¬ìš© ë° [CustomIconView ê°œë°œ](https://jsl663.tistory.com/43)
          - ë‹¤ì–‘í•œ [ì»¤ìŠ¤í…€ë·° ë° Animation/Transition](https://jsl663.tistory.com/49) ì„ í™œìš©í•˜ì—¬ ë””ìì¸ ì™„ì„±ë„ í–¥ìƒ

  # Side Projects
  - title: Side Projects
    layout: list
    content:
      # ì¹´ì¹´ì˜¤ë²„ìŠ¤ í´ë¡  ì•±
      - layout: left
        title: ì¹´ì¹´ì˜¤ë²„ìŠ¤ í´ë¡  ì•±
        caption: 2019.09 - 2022.11
        sub_title: Android
#        link: https://github.com/dev-loggi/kakaobus-clone
#        link_text: Github Link
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/dev-loggi/kakaobus-clone
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/mzymEDLK_8I
        quote: >
          ì¹´ì¹´ì˜¤ë²„ìŠ¤ ì•± ì¼ë¶€ ê¸°ëŠ¥ ë° í™”ë©´ ìµœëŒ€í•œ ë¹„ìŠ·í•˜ê²Œ êµ¬í˜„í•´ë³´ê¸°
        description: |
          __`Android` `Kotlin` `MVP`__
          - ê³µê³µ ë°ì´í„° í¬í„¸ ë‚´ "ì •ë¥˜ì†Œ ë° ë²„ìŠ¤ ë„ì°© ì •ë³´ API" ì—°ë™
          - ì •ë¥˜ì†Œ ê²€ìƒ‰, ì •ë¥˜ì†Œ ë³„ ë²„ìŠ¤ ë…¸ì„  ë° ì‹¤ì‹œê°„ ë„ì°© ì •ë³´ ì•ˆë‚´, ë²„ìŠ¤ ë…¸ì„  ë° ì •ë¥˜ì†Œ ì¦ê²¨ì°¾ê¸°, ìŠ¹ì°¨ ì•Œë¦¼ ê¸°ëŠ¥ êµ¬í˜„
          - ë²„ìŠ¤ ë…¸ì„  ë³„ ì˜ˆìƒ ë„ì°© ì‹œê°„ì„ **ë§¤ ì´ˆë§ˆë‹¤ ì‹¤ì‹œê°„ìœ¼ë¡œ ê°±ì‹ **í•˜ëŠ” **íƒ€ì´ë¨¸ êµ¬í˜„**
      # WATCHA í´ë¡  ì•±
      - layout: left
        title: WATCHA í´ë¡  ì•±
        caption: 2019.02 - 2019.04
        sub_title: Android
#        link: https://github.com/dev-loggi/watcha-clone
#        link_text: Github Link
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/dev-loggi/watcha-clone
          - title: YouTube Link
            icon: fab fa-youtube
            url: https://youtu.be/lfmCE_RQ7pY
        quote: >
          ì˜í™” OTT ì„œë¹„ìŠ¤ WATCHA ì•± ì¼ë¶€ ê¸°ëŠ¥ ë° í™”ë©´ ìµœëŒ€í•œ ë¹„ìŠ·í•˜ê²Œ êµ¬í˜„í•´ë³´ê¸°
        description: |
          __`Android` `Kotlin` `MVP`__
          - ë©”ì¸ í™”ë©´, ì˜í™” ê²€ìƒ‰, ì˜í™” ë””í…Œì¼ ì •ë³´, í‰ì  ë§¤ê¸°ê¸°, ë™ì˜ìƒ í”Œë ˆì´ì–´ ê¸°ëŠ¥ êµ¬í˜„
          - **Animation & Transition** íš¨ê³¼ êµ¬í˜„
          - ë™ì˜ìƒ í”Œë ˆì´ì–´ì— **Exoplayer** ë¼ì´ë¸ŒëŸ¬ë¦¬ í™œìš©. **í„°ì¹˜ ì¸í„°í˜ì´ìŠ¤** êµ¬í˜„
          

  # Skills
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Android
        sub_title: (ì¤‘ê¸‰)
        description: |
          - Kotlin, Java
          - Multi Module, Clean Architecture, Repository Pattern, MVVM, MVP
          - Jetpack AAC (ViewModel, LiveData, DataBinding, Lifecycles, Navigation)
          - Dagger Hilt
          - Retrofit2, Okhttp3, Coroutines, Flow
          - Room, Datastore
          - CustomView, Animator, LayoutTransition, MotionLayout, Material Design 3
      - layout: left
        title: Backend
        sub_title: (í•˜ê¸‰)
        description: |
          - AWS EC2, S3
          - NGINX, uWSGI
          - Django, Python
          - REST API, JWT
      - layout: left
        title: AI
        sub_title: (í•˜ê¸‰)
        description: |
          - Python, Jupyter Notebook
          - numpy, pandas, matplotlib, seaborn
          - Scikit-learn, Keras, Tensorflow
          - ML, DL(NLP, CV)
      - layout: left
        title: Frontend
        sub_title: (ê¸°ì´ˆ)
        description: |
          - HTML, CSS, JavaScript
          - Chrome Extensions

  # Certificates
  - title: Certificates
    layout: list
    content:
      - layout: left
        title: AICE (Associate)
        sub_title: ãˆœì¼€ì´í‹°, ãˆœí•œêµ­ê²½ì œì‹ ë¬¸ ê³µë™
        caption: 2023.04.21
        link: https://aice.study/
        description: |
          - AICE (AI Certificate for Everyone) ì¸ê³µì§€ëŠ¥ í™œìš©ëŠ¥ë ¥ í‰ê°€ ìê²©ì¦
          - ë°ì´í„° ë¶„ì„, ë°ì´í„° ì „ì²˜ë¦¬, ë¨¸ì‹ ëŸ¬ë‹/ë”¥ëŸ¬ë‹ ëª¨ë¸ë§, ëª¨ë¸ ì„±ëŠ¥ í‰ê°€
          - Scikit-learn, Tensorflow

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
