# Site
repository: dev-loggi/dev-loggi.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: ì¡°ì„±ë¡
title: Android Developer
email: jsl663663@gmail.com
website: github.com/dev-loggi

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: dev-loggi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: ë¸”ë¡œê·¸
  icon: fas fa-blog
  url: https://jsl663.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ì•ˆë…•í•˜ì„¸ìš”. ë””ìì¸ì— ìš•ì‹¬ì´ ë§ì€ ì•ˆë“œë¡œì´ë“œ ê°œë°œì ì¡°ì„±ë¡ì…ë‹ˆë‹¤.<br/>
  Android Modern UI/UX ê´€ì‹¬ê³¼ ì´í•´ë„ê°€ ë†’ìŠµë‹ˆë‹¤.<br/>
  Kotlin, OOP, Design Pattern, Functional Programming, Clean Code, Clean Architecture<br/>
  ì†Œí”„íŠ¸ì›¨ì–´ ì•„í‚¤í…ì²˜ì™€ í”„ë¡œê·¸ë˜ë° íŒ¨ëŸ¬ë‹¤ì„ì— ê´€ì‹¬ì´ ë§ìŠµë‹ˆë‹¤.

content:
  # Experience
  - title: Experience
    layout: list
    content:
      - layout: left
        title: íŒê²Œì•„ì†”ë£¨ì…˜
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: ì•ˆë“œë¡œì´ë“œ ì•± ê°œë°œ (ì¸í„´)
        caption: 2017.03 - 2017.08
        quote: >
          ì†Œì…œ ëª©í‘œ ì¼ê¸° "GoalGetter" SNS ì•ˆë“œë¡œì´ë“œ ì•± ì„œë¹„ìŠ¤ ê°œë°œ
        description: |
          - 6ê°œì›” ì¸í„´ì‹­ ê¸°ê°„ ë™ì•ˆ ê°œë°œí•˜ì—¬ ìŠ¤í† ì–´ì— ì¶œì‹œí•œ ì²« ì‹¤ë¬´ ì•±
          - íšŒì›, ê²Œì‹œë¬¼, ë©”ì‹ ì €, ê´‘ê³  ë“± ì´ 23ê°œ í™”ë©´ ë° ê¸°ëŠ¥ ê°œë°œ
          - SQLiteë¥¼ í™œìš©í•˜ì—¬ ë©”ì‹ ì € ì„±ëŠ¥ ê°œì„ 

  # Education
  - title: Education
    layout: list
    content:
      - layout: left
        title: KT AIVLE School 3ê¸°
        caption: 2023.02 - 2023.07
        sub_title: KT
        description: |
          - AI ëª¨ë¸ë§ì„ ìœ„í•œ ë°ì´í„° ë¶„ì„, ë¨¸ì‹ ëŸ¬ë‹, ë”¥ëŸ¬ë‹(CV, NLP) ì´ë¡  ë° ì‹¤ìŠµ
          - AI ì„œë¹„ìŠ¤ ê°œë°œì„ ìœ„í•œ MLOps, FE, BE, AWS í´ë¼ìš°ë“œ ì´ë¡  ë° ì‹¤ìŠµ
          - êµê³¼ëª©ë³„ í•™ìŠµ ê³¼ì •ì— ëŒ€í•œ ì‹¤ìŠµì„ ìœ„í•œ ë¯¸ë‹ˆ í”„ë¡œì íŠ¸ ìˆ˜í–‰
          - ë¹…í”„ë¡œì íŠ¸ - AI ê¸°ë°˜ ëŒ€í˜•ìƒí™œíê¸°ë¬¼ ê°„í¸ ë°°ì¶œ ì•± â€œí¼ë‹ˆë²„ë‹ˆâ€ (ìš°ìˆ˜ìƒğŸ†)
      - layout: left
        title: SW ì•Œê³ ë¦¬ì¦˜ íŠ¹ê°•
        caption: 2022.07 - 2023.08
        sub_title: ì‚¼ì„±ì „ì
        description: |
          - SW ìë£Œêµ¬ì¡° ë° ì•Œê³ ë¦¬ì¦˜ ì´ë¡  ê°•ì˜ ë° ì‹¤ì „ ë¬¸ì œ í’€ì´
          - ì£¼ì–´ì§„ ë¬¸ì œì— ì í•©í•œ ìë£Œêµ¬ì¡°ë¥¼ ì§ì ‘ ì„¤ê³„ ë° êµ¬í˜„
          - SW Expert Academy - Professional(Level B) ì·¨ë“

  # Projects
  - title: Projects
    layout: list
    content:
      - layout: left
        title: í¼ë‹ˆë²„ë‹ˆ
        caption: 2023.06 - 2023.07
        sub_title: Tech Lead, Android
        additional_links:
          - title: KT-AIVLE-3rd-AI-Team10/funibuni-fe-android
            icon: fab fa-github
            url: https://github.com/KT-AIVLE-3rd-AI-Team10/funibuni-fe-android
        quote: >
          AI ê¸°ë°˜ ëŒ€í˜•ìƒí™œíê¸°ë¬¼ ê°„í¸ ë°°ì¶œ ì•±
        description: |
          - KT AIVLE School 6ì¸ íŒ€ í”„ë¡œì íŠ¸ (ìš°ìˆ˜ìƒğŸ†)
          - AI ëª¨ë¸ ì„¤ê³„, ì‹œìŠ¤í…œ ì•„í‚¤í…ì²˜, ERD, API ì„¤ê³„, í…ŒìŠ¤íŠ¸, ì„œë²„ êµ¬ì¶• ë“± ê°œë°œ ê¸°ìˆ  ì½”ì¹˜ ë‹´ë‹¹
          - Clean Architecture, MVVM, Repository íŒ¨í„´ í™œìš©í•˜ì—¬ ê´€ì‹¬ì‚¬ ë¶„ë¦¬
          - ê³µí†µ Design System ëª¨ë“ˆí™”

  # Skills
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Android (ì¤‘)
        description: |
          - Kotlin, Java
          - Multi Module, Clean Architecture, Repository Pattern, MVVM, MVP
          - Jetpack AAC (ViewModel, LiveData, DataBinding), Navigation
          - Dagger Hilt
          - Retrofit2, Okhttp3, Coroutines Flow
          - Room, Datastore
      - layout: left
        title: Backend (í•˜)
        description: |
          - AWS EC2, S3, RDS
          - NGINX, uWSGI
          - Django, Python
          - REST API, JWT
      - layout: left
        title: Frontend (ê¸°ì´ˆ)
        description: |
          - HTML, CSS, Javascript
          - Chrome Extensions

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag